config/routes.rb
Rails.application.routes.draw do
  resources :order_details
  resources :orders
  resources :customers
  resources :foods
  resources :categories
  get 'reports', to: 'orders#report'
  # get 'categories/index'
  # get 'categories/show'
  # get 'categories/new'
  # get 'categories/edit'  
  # get 'foods/index'
  # get 'foods/show'
  # get 'foods/new'
  # get 'foods/edit'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :food

    validates :order_id, presence: true
    validates :food_id, presence: true
    validates :quantity, presence: true, numericality: true

    before_create :find_food_price

    def find_food_price
        Food.by_id(self.food_id).each do |food|
            self.price = food.price.to_i
        end
    end

    def find_food_name
        Food.by_id(self.food_id).each do |food|
            return food.name
        end
    end

    def count_total_price
        total = self.quantity * self.price
    end

    def self.by_order_id(id)
        where("order_id = #{id}").order(:order_id)
    end
end

app/controllers/order_details_controller.rb
class OrderDetailsController < ApplicationController
  before_action :set_order_detail, only: %i[ show edit update destroy ]

  # GET /order_details or /order_details.json
  def index
    @order_details = params[:id].nil? ? OrderDetail.all : OrderDetail.by_order_id(params[:id])
  end

  # GET /order_details/1 or /order_details/1.json
  def show
  end

  # GET /order_details/new
  def new
    @order_detail = OrderDetail.new
  end

  # GET /order_details/1/edit
  def edit
  end

  # POST /order_details or /order_details.json
  def create
    @order_detail = OrderDetail.new(order_detail_params)

    respond_to do |format|
      if @order_detail.save
        format.html { redirect_to order_detail_url(@order_detail), notice: "Order detail was successfully created." }
        format.json { render :show, status: :created, location: @order_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_details/1 or /order_details/1.json
  def update
    respond_to do |format|
      if @order_detail.update(order_detail_params)
        format.html { redirect_to order_detail_url(@order_detail), notice: "Order detail was successfully updated." }
        format.json { render :show, status: :ok, location: @order_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_details/1 or /order_details/1.json
  def destroy
    @order_detail.destroy

    respond_to do |format|
      format.html { redirect_to order_details_url, notice: "Order detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_detail
      @order_detail = OrderDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_detail_params
      params.require(:order_detail).permit(:order_id, :food_id, :price, :quantity)
    end
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/views/order_details/_form.html.erb
<%= form_with(model: order_detail) do |form| %>
  <% if order_detail.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order_detail.errors.count, "error") %> prohibited this order_detail from being saved:</h2>

      <ul>
        <% order_detail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">    
    <div class="card col-md-8 mx-auto">
      <div class="card-body">
        <form>
          <div class="d-flex justify-content-end">
          <%= link_to "Back to order", :back, class: "btn-sm btn-secondary " %>
          </div>
          <div class="mb-3 mt-2">
            <%= form.hidden_field :order_id, class: "form-control", value: session[:order_id] %>
            <%= form.label :food_id, style: "display: block", class: "form-label" %>
            <%= form.select :food_id, Food.all.pluck(:name, :id), {prompt: 'Select food'}, {class: "form-control", id: "food"} %>
          </div>
          <div class="mb-3">
            <%= form.label :quantity, style: "display: block", class: "form-label" %>
            <%= form.number_field :quantity, class: "form-control" %>
          </div>       
          <div>
            <%= form.submit :submit, class: "btn btn-primary" %>
          </div>
        </form>
      </div>
    </div>
  </div>
<% end %>

app/views/order_details/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-info">
  <div class="container">
    <h1 class="navbar-brand">
      <%= link_to "Foods", foods_path, style: "color: white; text-decoration: none; "%>
      |
      <%= link_to "Customers", customers_path, style: "color: white; text-decoration: none; "%>
      |
      <%= link_to "Orders", orders_path, style: "color: white; text-decoration: none; "%>
      |
      <%= link_to "Categories", categories_path, style: "color: white; text-decoration: none; "%>
    </h1>    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>    
  </div>
</nav>

app/views/order_details/_order_detail.html.erb
<div id="<%= dom_id order_detail %>">
  <p>
    <strong>Order:</strong>
    <%= order_detail.order_id %>
  </p>

  <p>
    <strong>Food:</strong>
    <%= order_detail.food_id %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= order_detail.price %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= order_detail.quantity %>
  </p>

</div>

app/views/order_details/edit.html.erb
<!--<%= render "navbar" %>-->

<div class="container mt-3">
  <div class="row">
    <div class="mx-auto mb-3"><h1>Edit Order Detail</h1></div>
  </div>

  <%= render "form", order_detail: @order_detail, category: @category %>

  <br>

  <div>
    <div class="container">
      <div class="row">
        <div class="mx-auto">
          <%= link_to "Show this order_detail", @order_detail, class: "btn btn-secondary" %>          
        </div>
      </div>
    </div>
  </div>
</div>

app/views/order_details/index.html.erb
<!--<%= render "navbar" %>-->
<div class="container mt-3">
  <div class="row">
    <div class="mx-auto">
      <p style="color: green"><%= notice %></p>
    </div>
  </div>
  <div class="d-flex justify-content-between mt-1">
    <div class="">
      <%= link_to "New order", new_order_detail_path, class: "btn btn-success" %>
    </div>
    <div class="">
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        Print Name
      </button>
    </div>
  </div>
  <div id="order_details" class="mt-2 mb-5">
    <table class="table table-striped">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Food</th>
          <th scope="col">Price</th>
          <th scope="col">Quantity</th>
          <th scope="col">Total</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <% 
        i = 0
        @order_details.each do |order_detail| 
        %>
          <tr>
            <td><%= i += 1 %></td>
            <td><%= order_detail.find_food_name %></td>
            <td><%= order_detail.price %></td>
            <td><%= order_detail.quantity %></td>
            <td><%= order_detail.count_total_price %></td>
            <td><%= link_to "Detail", order_detail %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>  
</div>

app/views/order_details/new.html.erb
<!--<%= render "navbar" %>-->
<div class="container mt-3">
  <div class="row">
    <div class="mx-auto mb-3"><h1>New Order Detail</h1></div>
  </div>
  <%= render "form", order_detail: @order_detail %>
</div>

app/views/order_details/show.html.erb
<!--<%= render "navbar" %>-->

<div class="container mt-5">
  <div class="row">
    <div class="mx-auto">
      <p style="color: green"><%= notice %></p>
    </div>
  </div>

  <% render @order_detail %>

  <div>
    <% link_to "Edit this order detail", edit_order_detail_path(@order_detail) %> <!-- | -->
    <% link_to "Back to order details", order_details_path %>

    <% button_to "Destroy this order detail", @order_detail, method: :delete %>
  </div>

  <div class="row">    
    <div class="card col-md-8 mx-auto">
      <div class="card-body">
        <form>          
          <div class="d-flex justify-content-between">
            <div><legend>Detail</legend></div>
          <div><%= link_to "Back to order", orders_path, class: "btn-sm btn-secondary" %>&nbsp;<%= link_to "Back to order_details", order_details_path, class: "btn-sm btn-secondary" %></div>
          </div>
          <div class="mb-3">
            <label class="form-label">Food ID</label>
            <input type="text" class="form-control" value="<%= @order_detail.food_id %>" readonly>            
          </div>
          <div class="mb-3">
            <label class="form-label">Price</label>
            <input type="text" class="form-control" value="<%= @order_detail.price %>" readonly>            
          </div>
          <div class="mb-3">
            <label class="form-label">Quantity</label>
            <input type="text" class="form-control" value="<%= @order_detail.quantity %>" readonly>            
          </div>
          <div class="d-flex justify-content-between">            
            <div class="">
              <%= link_to "Edit this order_detail", edit_order_detail_path(@order_detail), class: "btn btn-warning" %>
            </div>
            <div class="invisible">
              <%= button_to "Destroy this order_detail", @order_detail, method: :delete, class: "btn btn-danger" %>
            </div>
          </div>
          <div class="mt-2">
            <%= link_to "Add order_detail food", new_order_detail_path(@order_detail), class: "btn btn-primary" %>
          </div>
          <div class="mt-2">
            <%= button_to "Destroy this order_detail", @order_detail, method: :delete, class: "btn btn-danger" %>
          </div> 
        </form>
      </div>
    </div>
  </div>
</div>