config/routes.rb
Rails.application.routes.draw do
  resources :order_details
  resources :orders
  resources :customers
  resources :foods
  resources :categories
  get 'reports', to: 'orders#report'
  # get 'categories/index'
  # get 'categories/show'
  # get 'categories/new'
  # get 'categories/edit'  
  # get 'foods/index'
  # get 'foods/show'
  # get 'foods/new'
  # get 'foods/edit'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :orders
    validates :name, presence: true
    validates :email, presence: true, format: /\w+@\w+\.{1}[a-zA-Z]{2,}/

    def self.by_id(id)
        where("id = #{id}").order(:id)
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]

  # GET /customers or /customers.json
  def index
    @customers = params[:id].nil? ? Customer.all : Customer.by_id(params[:id])
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:name, :email, :phone)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div id="<%= dom_id customer %>">
  <p>
    <strong>Name:</strong>
    <%= customer.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= customer.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= customer.phone %>
  </p>

</div>

app/views/customers/_form.html.erb
<%= form_with(model: customer) do |form| %>
  <% if customer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">    
    <div class="card col-md-8 mx-auto">
      <div class="card-body">
        <form>
          <div class="d-flex justify-content-end">
          <%= link_to "Back to customers", customers_path, class: "btn-sm btn-secondary " %>
          </div>
          <div class="mb-3 mt-2">
            <%= form.label :name, style: "display: block", class: "form-label" %>
            <%= form.text_field :name, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= form.label :email, style: "display: block", class: "form-label" %>
            <%= form.text_field :email, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= form.label :phone, style: "display: block", class: "form-label" %>
            <%= form.number_field :phone, class: "form-control" %>
          </div>
          <div>
            <%= form.submit :submit, class: "btn btn-primary" %>
          </div>
        </form>
      </div>
    </div>
  </div>
<% end %>

app/views/customers/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <div class="container">
      <h1 class="navbar-brand">
        <%= link_to "Foods", foods_path, style: "color: white; text-decoration: none; "%>
        |
        <%= link_to "Customers", customers_path, style: "color: white; text-decoration: none; "%>
        |
        <%= link_to "Orders", orders_path, style: "color: white; text-decoration: none; "%>
      </h1>    
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>    
    </div>
</nav>

app/views/customers/edit.html.erb
<!--<%= render "navbar" %>-->

<div class="container mt-3">
  <div class="row">
    <div class="mx-auto mb-3"><h1>Edit Customer</h1></div>
  </div>

  <%= render "form", customer: @customer %>

  <br>

  <div>
    <div class="container">
      <div class="row">
        <div class="mx-auto">
          <%= link_to "Show this customer", @customer, class: "btn btn-secondary" %>          
        </div>
      </div>
    </div>
  </div>
</div>

app/views/customers/index.html.erb
<!--<%= render "navbar" %>-->
<div class="container mt-3">
  <div class="row">
    <div class="mx-auto">
      <p style="color: green"><%= notice %></p>
    </div>
  </div>
  <div class="d-flex justify-content-between mt-1">
    <div class="">
      <%= link_to "New customer", new_customer_path, class: "btn btn-success" %>
    </div>
    <div class="">
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        Print Name
      </button>
    </div>
  </div>
  <div id="customers" class="mt-2 mb-5">
    <table class="table table-striped">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">Phone</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <% 
        i = 0
        @customers.each do |customer| 
        %>
          <tr>
            <td><%= i += 1 %></td>
            <td><%= customer.name %></td>
            <td><%= customer.email %></td>
            <td><%= customer.phone %></td>
            <td><%= link_to "Detail", customer %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>  
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header bg-info text-white">
        <h5 class="modal-title" id="exampleModalLabel">All customers</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% @customers.each do |customer| %>
          <p><%= customer.name %></p>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/customers/new.html.erb
<!--<%= render "navbar" %>-->
<div class="container mt-3">
  <div class="row">
    <div class="mx-auto mb-3"><h1>New Customer</h1></div>
  </div>
  <%= render "form", customer: @customer %>
</div>

app/views/customers/show.html.erb
<!--<%= render "navbar" %>-->

<div class="container mt-5">
<div class="row">
  <div class="mx-auto">
    <p style="color: green"><%= notice %></p>
  </div>
</div>

<% render @customer %>

<div>
  <% link_to "Edit this customer", edit_customer_path(@customer) %> <!-- | -->
  <% link_to "Back to customers", customers_path %>

  <% button_to "Destroy this customer", @customer, method: :delete %>
</div>

  <div class="row">    
    <div class="card col-md-8 mx-auto">
      <div class="card-body">
        <form>          
          <div class="d-flex justify-content-between">
            <div><legend>Detail</legend></div>
          <div><%= link_to "Back to customers", customers_path, class: "btn-sm btn-secondary" %></div>
          </div>
          <div class="mb-3">
            <label class="form-label">Name</label>
            <input type="text" class="form-control" value="<%= @customer.name%>" readonly>            
          </div>
          <div class="mb-3">
            <label class="form-label">Email</label>
            <input type="text" class="form-control" value="<%= @customer.email%>" readonly>            
          </div>
          <div class="mb-3">
            <label class="form-label">Phone</label>
            <input type="number" class="form-control" value="<%= @customer.phone%>" readonly>            
          </div>
          <div class="d-flex justify-content-between">
            <div class="">
              <%= link_to "Edit this customer", edit_customer_path(@customer), class: "btn btn-warning" %>
            </div>
            <div class="invisible">
              <%= button_to "Destroy this customer", @customer, method: :delete, class: "btn btn-danger" %>
            </div>
          </div>
          <div class="mt-2">
            <%= button_to "Destroy this customer", @customer, method: :delete, class: "btn btn-danger" %>
          </div> 
        </form>
      </div>
    </div>
  </div>
</div>