config/routes.rb
Rails.application.routes.draw do
  resources :order_details
  resources :orders
  resources :customers
  resources :foods
  resources :categories
  get 'reports', to: 'orders#report'
  # get 'categories/index'
  # get 'categories/show'
  # get 'categories/new'
  # get 'categories/edit'  
  # get 'foods/index'
  # get 'foods/show'
  # get 'foods/new'
  # get 'foods/edit'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_details

    validates :customer_id, presence: true

    def find_customer
        Customer.by_id(self.customer_id).each do |customer|
            return customer.email
        end
    end

    def self.report_today
        where("order_date LIKE ?", "#{Date.current}%").order(:id)
    end

    def find_by_email(email)
        where("email LIKE ?", "#{email}%").order(:id)
    end

    def count_total_price
        total = []
        OrderDetail.by_order_id(self.id).each do |order_detail|
            total << order_detail.quantity * order_detail.price
        end
        return total.inject(0){ |sum, x| sum + x}
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def report
    @reports = params[:email].nil? ? Order.report_today : Order.find_by_email(params[:email])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:customer_id, :order_date, :status)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">    
    <div class="card col-md-8 mx-auto">
      <div class="card-body">
        <form>
          <div class="d-flex justify-content-end">
          <%= link_to "Back to orders", orders_path, class: "btn-sm btn-secondary " %>
          </div>
          <div class="mb-3 mt-2">
            <%= form.label :customer_id, style: "display: block", class: "form-label" %>
            <%= form.select :customer_id, Customer.all.pluck(:email, :id), {prompt: 'Select customer'}, {class: "form-control"} %>
          </div>
          <div class="mb-3">
            <%= form.label :order_date, style: "display: block", class: "form-label" %>
            <%= form.date_field :order_date, value: (form.object.order_date || Time.now.strftime('%Y-%m-%d')), class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= form.label :status, style: "display: block", class: "form-label" %>
            <%= form.select :status, ['NEW', 'PAID', 'CANCELED'], {prompt: 'Select status'}, {class: "form-control"} %>
          </div>          
          <div>
            <%= form.submit :submit, class: "btn btn-primary" %>
          </div>
        </form>
      </div>
    </div>
  </div>
<% end %>

app/views/orders/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-info">
  <div class="container">
    <h1 class="navbar-brand">
      <%= link_to "Foods", foods_path, style: "color: white; text-decoration: none; "%>
      |
      <%= link_to "Customers", customers_path, style: "color: white; text-decoration: none; "%>
      |
      <%= link_to "Orders", orders_path, style: "color: white; text-decoration: none; "%>
      |
      <%= link_to "Categories", categories_path, style: "color: white; text-decoration: none; "%>
      |
      <%= link_to "Report", 'reports', style: "color: white; text-decoration: none; "%>
    </h1>    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>    
  </div>
</nav>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <% session[:order_id] = order.id %>
  <p>
    <strong>Customer email:</strong>
    <%= order.customer_id %>
  </p>

  <p>
    <strong>Order date:</strong>
    <%= order.order_date %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= order.status %>
  </p>

</div>

app/views/orders/edit.html.erb
<!--<%= render "navbar" %>-->

<div class="container mt-3">
  <div class="row">
    <div class="mx-auto mb-3"><h1>Edit Order</h1></div>
  </div>

  <%= render "form", order: @order, category: @category %>

  <br>

  <div>
    <div class="container">
      <div class="row">
        <div class="mx-auto">
          <%= link_to "Show this order", @order, class: "btn btn-secondary" %>          
        </div>
      </div>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
<!--<%= render "navbar" %>-->
<div class="container mt-3">
  <div class="row">
    <div class="mx-auto">
      <p style="color: green"><%= notice %></p>
    </div>
  </div>
  <div class="d-flex justify-content-between mt-1">
    <div class="">
      <%= link_to "New order", new_order_path, class: "btn btn-success" %>
    </div>
    <div class="">
      <%= link_to "All Detail Orders", order_details_path, class: "btn btn-primary" %>
    </div>
  </div>
  <div id="orders" class="mt-2 mb-5">
    <table class="table table-striped">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Date</th>
          <th scope="col">Customer Email</th>
          <th scope="col">Status</th>
          <th scope="col">Total</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <% 
        i = 0
        @orders.each do |order| 
        %>
          <tr>
            <td><%= i += 1 %></td>
            <td><%= order.order_date %></td>
            <td><%= order.find_customer %></td>
            <td><%= order.status %></td>
            <td><%= order.count_total_price %></td>
            <td><%= link_to "Order Food", new_order_detail_path %> | <%= link_to "Detail", order %> | <%= link_to "Detail Order", "order_details/?id=#{order.id}" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>  
</div>

app/views/orders/new.html.erb
<!--<%= render "navbar" %>-->
<div class="container mt-3">
  <div class="row">
    <div class="mx-auto mb-3"><h1>New Order</h1></div>
  </div>
  <%= render "form", order: @order %>
</div>

app/views/orders/report.html.erb
<!--<%= render "navbar" %>-->
<div class="container mt-3">
  <div class="row">
    <div class="mx-auto">
      <p style="color: green"><%= notice %></p>
    </div>
  </div>
  <div class="d-flex justify-content-between mt-1">
    <div class="">
      <h1>Report Order <%= Date.current %></h1>
    </div>
  </div>
  <div id="reports" class="mt-2 mb-5">
    <table class="table table-striped">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Date</th>
          <th scope="col">Customer Email</th>
          <th scope="col">Status</th>
          <th scope="col">Total</th>
        </tr>
      </thead>
      <tbody>
        <% 
        i = 0
        @reports.each do |report| 
        %>
          <tr>
            <td><%= i += 1 %></td>
            <td><%= report.order_date %></td>
            <td><%= report.find_customer %></td>
            <td><%= report.status %></td>
            <td><%= report.count_total_price %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>  
</div>

app/views/orders/show.html.erb
<!--<%= render "navbar" %>-->

<div class="container mt-5">
  <div class="row">
    <div class="mx-auto">
      <p style="color: green"><%= notice %></p>
    </div>
  </div>

  <% render @order %>

  <div>
    <% link_to "Edit this order", edit_order_path(@order) %> <!-- | -->
    <% link_to "Back to orders", orders_path %>

    <% button_to "Destroy this order", @order, method: :delete %>
  </div>

  <div class="row">    
    <div class="card col-md-8 mx-auto">
      <div class="card-body">
        <form>          
          <div class="d-flex justify-content-between">
            <div><legend>Detail</legend></div>
          <div><%= link_to "Back to orders", orders_path, class: "btn-sm btn-secondary" %></div>
          </div>
          <div class="mb-3">
            <label class="form-label">Customer Name</label>
            <input type="text" class="form-control" value="<%= @order.customer_id %>" readonly>            
          </div>
          <div class="mb-3">
            <label class="form-label">Order Date</label>
            <input type="text" class="form-control" value="<%= @order.order_date %>" readonly>            
          </div>
          <div class="mb-3">
            <label class="form-label">Status</label>
            <input type="text" class="form-control" value="<%= @order.status %>" readonly>            
          </div>
          <div class="d-flex justify-content-between">            
            <div class="">
              <%= link_to "Edit this order", edit_order_path(@order), class: "btn btn-warning" %>
            </div>
            <div class="invisible">
              <%= button_to "Destroy this order", @order, method: :delete, class: "btn btn-danger" %>
            </div>
          </div>
          <div class="mt-2">
            <%= link_to "Add order food", new_order_detail_path(@order_detail), class: "btn btn-primary" %>
          </div>
          <div class="mt-2">
            <%= button_to "Destroy this order", @order, method: :delete, class: "btn btn-danger" %>
          </div> 
        </form>
      </div>
    </div>
  </div>
</div>