config/routes.rb
Rails.application.routes.draw do
  resources :order_details
  resources :orders
  resources :customers
  resources :foods
  resources :categories
  get 'reports', to: 'orders#report'
  # get 'categories/index'
  # get 'categories/show'
  # get 'categories/new'
  # get 'categories/edit'  
  # get 'foods/index'
  # get 'foods/show'
  # get 'foods/new'
  # get 'foods/edit'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRuby3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <div class="container">
      <h1 class="navbar-brand">
        <%= link_to "Foods", foods_path, style: "color: white; text-decoration: none; "%>
        |
        <%= link_to "Customers", customers_path, style: "color: white; text-decoration: none; "%>
        |
        <%= link_to "Orders", orders_path, style: "color: white; text-decoration: none; "%>
        |
        <%= link_to "Categories", categories_path, style: "color: white; text-decoration: none; "%>
        |
        <%= link_to "Reports", reports_path, style: "color: white; text-decoration: none; "%>
      </h1>    
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>    
    </div>
  </nav>
    <%= yield %>
  </body>
</html>